apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-idp-backstage
  description: The Backstage portal for the AWS Internal Developer Platform
  annotations:
    github.com/project-slug: tetevi/aws_idp_backstage
spec:
  type: website
  lifecycle: experimental
  owner: tetevi